[package]
name = "mimdb"
version = "0.1.0"
edition = "2024"
description = "A Columnar Analytical Database Library"
license-file = "LICENSE.md"

[lib]
name = "mimdb"
path = "src/lib.rs"

[dependencies]
zstd = "0.13"
lz4_flex = "0.11"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
anyhow = "1.0"

[[bin]]
name = "generate_examples"
path = "bin/generate_examples.rs"

[[bin]]
name = "loader"
path = "bin/loader.rs"

[dev-dependencies]
tempfile = "3.0"
